name: HipixelCore
main: notthatuwu.hipixel.core.Main
version: 0.0.1
author: NotThatUwU
depend:
  - ProtocolLib
commands:

  gamemode:
    description: change gamemodes
    aliases: [gm]
    usage: /<command> <survival|creative|adventure|spectator> [player]

  creative:
    description: change gamemodes
    aliases: [gmc]
    usage: /<command> [player]

  survival:
    description: change gamemodes
    aliases: [gms]
    usage: /<command> [player]

  adventure:
    description: change gamemodes
    aliases: [gma]
    usage: /<command> [player]

  spectator:
    description: change gamemodes
    aliases: [gmsp]
    usage: /<command> [player]

  fly:
    description: fly
    usage: /<command> [player]

  speed:
    description: speed
    usage: /<command> [value]

permissions:
  hipixelcore.gamemodes:
    description: Change Gamemode permissions
    default: op
  hipixelcore.gamemodes.other:
    description: Change Gamemode permissions
    default: op
  hipixelcore.pluginhider.bypass:
    description: Make u able to see plugins
    default: op
  hipixelcore.fly:
    description: Make u Fly
    default: op
  hipixelcore.fly.other:
    description: other ppl Fly
    default: op
  hipixelcore.speed:
    description: Fly speed
    default: op
  hipixelcore.chatcolor:
    description: Color
    default: op